#!/usr/bin/env bash
# display info about subdomains
domain=$1
if [ $# -eq 1 ]; then
    subdomains=("www" "lb-01" "web-01" "web-02")
    
    for subdomain in ${subdomains[@]}; do
        record="$(dig "$subdomain.$domain" | grep -A1 'ANSWER SECTION:' | tail -1 | awk '{print $4}')"
        ip="$(dig "$subdomain.$domain" | grep -A1 'ANSWER SECTION:' | tail -1 | awk '{print $5}')"
        echo "The subdomain $subdomain is a $record record and points to $ip"
    done
    
else
    subdomain="$2"
    record="$(dig "$subdomain.$domain" | grep -A1 'ANSWER SECTION:' | tail -1 | awk '{print $4}')"
    ip="$(dig "$subdomain.$domain" | grep -A1 'ANSWER SECTION:' | tail -1 | awk '{print $5}')"
    echo "The subdomain $subdomain is a $record record and points to $ip"
fi
